server:
  port: 8080

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?characterEncoding=utf8&useSSL=false
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: lirendada.art:8848
        cluster-name: SH   # 集群名称: 上海集群
#        ephemeral: false  # 设置为非临时实例
        namespace: 16cb6cdb-bc75-438b-a7a1-205b9a0afbd9  # 命名空间ID
    loadbalancer:
      nacos:
        enabled: true # 开启nacos的负载均衡策略

mybatis:
  configuration:
    # 配置打印 MyBatis 日志
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #配置驼峰自动转换