server:
  port: 8080

spring:
  profiles:
    active: @profile.name@  # Maven 打包时替换为 dev 或 prod
  application:
    name: user-info-service
  cloud:
    loadbalancer:
      nacos:
        enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 60s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5s
  rabbitmq:
    port: 5672
    username: admin
    password: 51gsd4fs
    virtual-host: blog
    listener:
      simple:
        acknowledge-mode: manual
  mail:
    host: smtp.qq.com
    port: 465
    username: 2916776007@qq.com
    password: tmatsqqndzoldgif
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      personal: "liren微服务系统"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_user?characterEncoding=utf8&useSSL=false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true