server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_user?characterEncoding=utf8&useSSL=false
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-info-service

  cloud:
    loadbalancer:
      nacos:
        enabled: true # 启动负载均衡
    nacos:
      discovery:
        server-addr: lirendada.art:8848 # nacos地址

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 60s #连接空闲超过N(s秒、ms毫秒)后关闭，0为禁用，这里配置值和tcp-keepalive值一致
      lettuce:
        pool:
          max-active: 8  #允许最大连接数
          max-idle: 8 #最大空闲连接数, 默认8
          min-idle: 0  #最小空闲连接数
          max-wait: 5s  #请求获取连接等待时间

  rabbitmq:
    host: lirendada.art
    port: 5672
    username: admin
    password: 51gsd4fs
    virtual-host: blog
    listener:
      simple:
        acknowledge-mode: manual # 消费者手动确认

  mail:
    host: smtp.qq.com
    port: 465
    username: 2916776007@qq.com
    password: tmatsqqndzoldgif   # 授权码，不是邮箱密码
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true     # ⭐ 核心
      mail.smtp.ssl.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      personal: "liren微服务系统"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    name: user.log