spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: liren
    password: Liren0324..
    driver-class-name: com.mysql.cj.jdbc.Driver