server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_blog?characterEncoding=utf8&useSSL=false
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: blog-info-service

  cloud:
    loadbalancer:
      nacos:
        enabled: true # 启动负载均衡
    nacos:
      discovery:
        server-addr: lirendada.art:8848 # nacos地址
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    name: blog.log