server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_product?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: liren
    password: Liren0324..
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: lirendada.art:8848
    loadbalancer:
      nacos:
        enabled: true      # 同样需要开启负载均衡策略

mybatis:
  configuration:
    # 配置打印 MyBatis 日志
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #配置驼峰自动转换